# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: KB Exchange Rate Parser

on:
  schedule:
    - cron: '* * * * *' 
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Parser with python
      run: |
        python "parser.py"
    - name: Commits
      run: |
        git config --local user.email "dev.devin.kr@gmail.com"
        git config --local user.name "yebin-choi" 
        git add .
        git commit -m "Auto - Update data with Parsing" 
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
